### PR TITLE
fix: add deprecated state for keyboards

### LINKED ISSUE #5: [api.keyman.com] Update deprecation flags in database to make querying faster and simpler
Currently, we mark deprecation with the `deprecates` relation. This gives us one direction. However, this requires a secondary query to determine whether a keyboard is deprecated, which is not ideal for searches. We should build the corresponding relation for each keyboard as a `deprecatedBy` relation. 

Then we need to update the search and cloud APIs to flag deprecated keyboards.

This work comes out of keymanapp/keyboards#374.

### LINKED ISSUE #7: Cloud keyboard searches do not ignore deprecated keyboards
Builds on #5. At present, searching for a keyboard in the database with the legacy searches does not exclude deprecated keyboards. It should.

### LINKED ISSUE #29: Add timing report to hooks/keyboard-build-success
Because this takes a while, it would be helpful for the report to giving details on what takes longest for future analysis.

Sample run currently:

```
Downloading https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
Downloading https://downloads.keyman.com/data/keyboard_info.zip
Downloading https://downloads.keyman.com/data/model_info.zip
Triggered database build for keymanapp/keyboards and keymanapp/lexical-models
=============================================================================

Running D:\home\site\wwwroot\tools\db\build/search.sql
Running D:\home\site\wwwroot\tools\db\build/search-queries.sql
Running D:\home\site\wwwroot\tools\db\build/model-queries.sql
Running D:\home\site\wwwroot\tools\db\build/legacy-queries.sql
Running D:\home\site\wwwroot/.data/language-subtag-registry.sql
Running D:\home\site\wwwroot/.data/iso639-3.sql
Running D:\home\site\wwwroot/.data/iso639-3-name-index.sql
Running D:\home\site\wwwroot/.data/ethnologue_language_codes.sql
Running D:\home\site\wwwroot/.data/ethnologue_country_codes.sql
Running D:\home\site\wwwroot/.data/ethnologue_language_index.sql
Running D:\home\site\wwwroot/.data/keyboards.sql
Running D:\home\site\wwwroot/.data/models.sql
Running D:\home\site\wwwroot\tools\db\build/search-prepare-data.sql
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Backend changes relating to keymanapp/keyman.com#62

Adds deprecation state to the database and surfaces it 
in the keyboard search. This leads to a slight difference
in .keyboard_info and API data.

Fixes #5.
Fixes #7.
Fixes #29.

## TODO
- [x] Update schema to include deprecated field
- [x] Document changes to results
- [x] Test locally (I need to setup a local replication)

### CODE REVIEW

File: tools/db/build/common.php [hunk 1]
```diff
@@ -10,9 +10,20 @@ function cache($url, $filename, $duration = 60 * 60 * 24 * 7, $do_force = false)
     if($local_force) $duration = 0;
     if(!file_exists($filename) || time()-filemtime($filename) > $duration) {
       echo "Downloading $url\n";
-      if(($file = @file_get_contents($url)) === FALSE) {
+      
+      // Create a stream
+      $opts = array(
+        'http'=>array(
+          'method'=>"GET",
+          'header'=>"User-Agent: api-keyman-com Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1\r\n"
```
Comment (mcdurdin) [inline tools/db/build/common.php]: Without a user agent, some sites would block file downloads
