### PR TITLE
fix: ignore deprecated keyboards in legacy APIs

### LINKED ISSUE #38: [cloud] Keyboard preference order appears to be incorrect
A language-code lookup of 'km' now default-returns Khmer (NiDA) ( basic_kbdkni) instead of Khmer Angkor ( khmer_angkor), and 'und-fonipa' returns the deprecated ipauni11 instead of sil_ipa keyboard.  I doubt it's intentional, but wonder what severity we'd call that.

IPA: https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=13.0.300&keyboardid=@und-fonipa&timerid=16

Khmer: https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=13.0.300&keyboardid=@km&timerid=18

Arose from KeymanWeb testing in keymanapp/keyman#2528.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #38.

Deprecated keyboards are no longer included in search results when using
the legacy APIs. This reduces the result set for Android, iOS and
KeymanWeb pickers.

Also, adds Linux platform data to the keyboard metadata.

### CODE REVIEW

File: tools/db/build/build_keyboards_script.php [hunk 1]
```diff
@@ -200,17 +204,20 @@ function generate_keyboard_inserts() {
...
-    
+
           {$this->sqlb($platform_windows)},
           {$this->sqlb($platform_macos)},
           {$this->sqlb($platform_ios)},
           {$this->sqlb($platform_android)},
           {$this->sqlb($platform_web)},
+          {$this->sqlb($platform_linux)},
+
+          0,
```
Comment (darcywong00) [inline tools/db/build/build_keyboards_script.php]: Is this the deprecated flag?

**Comment by mcdurdin** [comment]
Yes

File: tools/db/build/build_keyboards_script.php (hunk 1 above)
Comment (mcdurdin) [reply tools/db/build/build_keyboards_script.php]: The deprecated flag gets set to 1 in the follow up script search-prepare-data.sql.

**Comment by mcdurdin** [comment]
Note: this doesn't change the order of keyboards presented (as noted in #38): that's something for the Language Picker feature coming up.
